name: bluebuild
on:
  schedule:
    - cron: "00 06 * * *" # 20 minutes after ublue images start building
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-base:
    name: Build vault-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Build vault-base
        uses: blue-build/github-action@v1.12
        with:
          recipe: vault-base.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true

  build-variants:
    name: Build ${{ matrix.recipe }}
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - vault-gnome.yml
          - vault-hyprland.yml
    steps:
      - name: Build ${{ matrix.recipe }}
        uses: blue-build/github-action@v1.12
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
